![OneHealth DataSpace](https://bigdata.dataspace.cesga.es/static/images/public/imagotipo.png)

> **⚠️ ADVERTENCIA**: actualmente a plataforma está en fase de proba. Agradecemos que nos fagades chegar calquera comentario a onehealth@cesga.es

# Cargando datos

Para comezar, importaremos o módulo onehealth para usar todas as funcionalidades:

In [1]:
import onehealth
import pyspark.sql.functions as F
from pyspark.sql.functions import col, expr
import pandas as pd

Agora podemos listar os conxuntos de datos dispoñibles coa función `list`:

In [2]:
onehealth.list()

Se queremos ter máis información sobre un conxunto de datos concreto podemos usar a función `describe`:

In [7]:
onehealth.describe("especies/ieo_capturas")

Finalmente podemos cargar o conxunto de datos que nos interese usando a función `load`:

In [8]:
capturas = onehealth.load("especies/ieo_capturas")

Agora que temos os datos cargados, xa podemos traballar con eles, por exemplo podemos ver cantas filas hai no conxunto de datos:

In [9]:
capturas.count()

337746

Ou ver explorar as primeiras filas do conxunto:

In [10]:
capturas.head(5)

[Row(id_observation='22', aphia_id_code='140600', cod_ieem='6483', id_spezie='125', x3a_code='EOI', scientific_name='Eledone cirrhosa', spanish_fao_name='Pulpo blanco', english_fao_name='Horned octopus', project='spezies, mapdescar', obs_date='2020-09-29', individuals='9', weight_gr='1070', weight_kg='1.07', depth='230', weight_gr_dum='1070', camp='N19', long_4326='-9.5382', lat_4326='42.784', geom='0101000020E6100000166A4DF38E1323C03108AC1C5A644540'),
 Row(id_observation='103', aphia_id_code='140600', cod_ieem='6483', id_spezie='125', x3a_code='EOI', scientific_name='Eledone cirrhosa', spanish_fao_name='Pulpo blanco', english_fao_name='Horned octopus', project='spezies, mapdescar', obs_date='2020-09-29', individuals='4', weight_gr='230', weight_kg='0.23', depth='114', weight_gr_dum='230', camp='N10', long_4326='-9.0427', lat_4326='41.974', geom='0101000020E610000012143FC6DC1522C0E9263108ACFC4440'),
 Row(id_observation='104', aphia_id_code='140600', cod_ieem='6483', id_spezie='125', x3a_code='EOI', scientific_name='Eledone cirrhosa', spanish_fao_name='Pulpo blanco', english_fao_name='Horned octopus', project='spezies, mapdescar', obs_date='2020-09-29', individuals='18', weight_gr='1448', weight_kg='1.448', depth='138', weight_gr_dum='1448', camp='N10', long_4326='-9.1271', lat_4326='42.0547', geom='0101000020E6100000A9A44E40134122C0AC8BDB6800074540'),
 Row(id_observation='105', aphia_id_code='140600', cod_ieem='6483', id_spezie='125', x3a_code='EOI', scientific_name='Eledone cirrhosa', spanish_fao_name='Pulpo blanco', english_fao_name='Horned octopus', project='spezies, mapdescar', obs_date='2020-09-29', individuals='10', weight_gr='475', weight_kg='0.475', depth='104', weight_gr_dum='475', camp='N10', long_4326='-8.9856', lat_4326='42.0859', geom='0101000020E61000000DE02D90A0F821C0FB5C6DC5FE0A4540'),
 Row(id_observation='106', aphia_id_code='140600', cod_ieem='6483', id_spezie='125', x3a_code='EOI', scientific_name='Eledone cirrhosa', spanish_fao_name='Pulpo blanco', english_fao_name='Horned octopus', project='spezies, mapdescar', obs_date='2020-09-29', individuals='7', weight_gr='1180', weight_kg='1.18', depth='133', weight_gr_dum='1180', camp='N10', long_4326='-9.0694', lat_4326='42.1569', geom='0101000020E61000004FAF9465882322C0075F984C15144540')]

In [11]:
capturas.limit(5).toPandas()

,id_observation,aphia_id_code,cod_ieem,id_spezie,x3a_code,scientific_name,spanish_fao_name,english_fao_name,project,obs_date,individuals,weight_gr,weight_kg,depth,weight_gr_dum,camp,long_4326,lat_4326,geom
0,22,140600,6483,125,EOI,Eledone cirrhosa,Pulpo blanco,Horned octopus,"spezies, mapdescar",2020-09-29,9,1070,1.07,230,1070,N19,-9.5382,42.784,0101000020E6100000166A4DF38E1323C03108AC1C5A64...
1,103,140600,6483,125,EOI,Eledone cirrhosa,Pulpo blanco,Horned octopus,"spezies, mapdescar",2020-09-29,4,230,0.23,114,230,N10,-9.0427,41.974,0101000020E610000012143FC6DC1522C0E9263108ACFC...
2,104,140600,6483,125,EOI,Eledone cirrhosa,Pulpo blanco,Horned octopus,"spezies, mapdescar",2020-09-29,18,1448,1.448,138,1448,N10,-9.1271,42.0547,0101000020E6100000A9A44E40134122C0AC8BDB680007...
3,105,140600,6483,125,EOI,Eledone cirrhosa,Pulpo blanco,Horned octopus,"spezies, mapdescar",2020-09-29,10,475,0.475,104,475,N10,-8.9856,42.0859,0101000020E61000000DE02D90A0F821C0FB5C6DC5FE0A...
4,106,140600,6483,125,EOI,Eledone cirrhosa,Pulpo blanco,Horned octopus,"spezies, mapdescar",2020-09-29,7,1180,1.18,133,1180,N10,-9.0694,42.1569,0101000020E61000004FAF9465882322C0075F984C1514...

# Cargando datos filtrados

> **⚠️ ADVERTENCIA**: Esta función non está actualmente dispoñible para todos os conxuntos de datos. Para calquera dúbida ou consulta, enviar unha petición a onehealth@cesga.es.

Facendo uso da función `load_partition` pódese seleccionar unha franxa de tempo a cargar.

In [14]:
roms_filtrado = onehealth.load_partition("modelos/meteogalicia_roms", 2014, 6, 2)

Mostramos as primeiras filas do resultado:

In [15]:
roms_filtrado.head(5)

[Row(lon_rho=-14.0, lat_rho=38.0, mask_rho=1.0, angle=9.969209968386869e+36, ocean_time=datetime.datetime(2014, 6, 4, 15, 0), zeta=-0.2534502446651459, u=0.02190525457262993, v=0.021844400092959404, temp=2.4600000381469727, salt=34.9370002746582, depth=4000.0, eta_rho=0, xi_rho=0, step=63),
 Row(lon_rho=-11.76, lat_rho=43.06, mask_rho=1.0, angle=9.969209968386869e+36, ocean_time=datetime.datetime(2014, 6, 4, 4, 0), zeta=-0.16161860525608063, u=-0.02839832568284751, v=-0.01371103876086682, temp=12.6061893676252, salt=35.674521614168576, depth=75.0, eta_rho=253, xi_rho=112, step=52),
 Row(lon_rho=-13.98, lat_rho=38.0, mask_rho=1.0, angle=9.969209968386869e+36, ocean_time=datetime.datetime(2014, 6, 4, 15, 0), zeta=-0.2534603774547577, u=0.021358972415328026, v=0.021211786195635796, temp=2.4609999656677246, salt=34.9370002746582, depth=4000.0, eta_rho=0, xi_rho=1, step=63),
 Row(lon_rho=-11.74, lat_rho=43.06, mask_rho=1.0, angle=9.969209968386869e+36, ocean_time=datetime.datetime(2014, 6, 4, 4, 0), zeta=-0.16120904684066772, u=-0.02919950865954356, v=-0.015958031603431726, temp=12.617370836290341, salt=35.67376272876774, depth=75.0, eta_rho=253, xi_rho=113, step=52),
 Row(lon_rho=-13.96, lat_rho=38.0, mask_rho=1.0, angle=9.969209968386869e+36, ocean_time=datetime.datetime(2014, 6, 4, 15, 0), zeta=-0.25260111689567566, u=0.017771858721971512, v=0.01598436012864113, temp=2.4570000171661377, salt=34.9370002746582, depth=4000.0, eta_rho=0, xi_rho=2, step=63)]

In [21]:
roms_filtrado.limit(5).withColumn("ocean_time", col("ocean_time").cast("string")).toPandas()

,lon_rho,lat_rho,mask_rho,angle,ocean_time,zeta,u,v,temp,salt,depth,eta_rho,xi_rho,step
0,-14.00,38.00,1.0,9.969210e+36,2014-06-04 15:00:00,-0.253450,0.021905,0.021844,2.460000,34.937000,4000.0,0,0,63
1,-11.76,43.06,1.0,9.969210e+36,2014-06-04 04:00:00,-0.161619,-0.028398,-0.013711,12.606189,35.674522,75.0,253,112,52
2,-13.98,38.00,1.0,9.969210e+36,2014-06-04 15:00:00,-0.253460,0.021359,0.021212,2.461000,34.937000,4000.0,0,1,63
3,-11.74,43.06,1.0,9.969210e+36,2014-06-04 04:00:00,-0.161209,-0.029200,-0.015958,12.617371,35.673763,75.0,253,113,52
4,-13.96,38.00,1.0,9.969210e+36,2014-06-04 15:00:00,-0.252601,0.017772,0.015984,2.457000,34.937000,4000.0,0,2,63