![OneHealth DataSpace](https://bigdata.dataspace.cesga.es/static/images/public/imagotipo.png)

> **⚠️ ADVERTENCIA**: actualmente a plataforma está en fase de proba. Agradecemos que nos fagades chegar calquera comentario a onehealth@cesga.es

# Explorando datos

Para comezar, importaremos algúns módulos que en xeral nos serán de utilidade:

In [ ]:
import onehealth
import pyspark.sql.functions as F
from pyspark.sql.functions import col, expr
import pandas as pd

Para obter máis información sobre un conxunto de datos concreto podemos usar a función `describe`:

In [ ]:
onehealth.describe("especies/ieo_capturas")

Información encontrada para el dataset csic/capturas:

Para facer exploracións cos datos, cargaremos o dataframe nunha variable para traballar máis cómodamente.

In [ ]:
capturas = onehealth.load("especies/ieo_capturas")

Agora que temos os datos cargados, xa podemos traballar con eles, por exemplo podemos ver cantas filas hai no conxunto de datos:

In [4]:
capturas.count()

337746

Ou ver explorar as primeiras filas do conxunto:

In [5]:
capturas.limit(5).toPandas()

,id_observation,aphia_id_code,cod_ieem,id_spezie,x3a_code,scientific_name,spanish_fao_name,english_fao_name,project,obs_date,individuals,weight_gr,weight_kg,depth,weight_gr_dum,camp,long_4326,lat_4326,geom
0,22,140600,6483,125,EOI,Eledone cirrhosa,Pulpo blanco,Horned octopus,"spezies, mapdescar",2020-09-29,9,1070,1.07,230,1070,N19,-9.5382,42.784,0101000020E6100000166A4DF38E1323C03108AC1C5A64...
1,103,140600,6483,125,EOI,Eledone cirrhosa,Pulpo blanco,Horned octopus,"spezies, mapdescar",2020-09-29,4,230,0.23,114,230,N10,-9.0427,41.974,0101000020E610000012143FC6DC1522C0E9263108ACFC...
2,104,140600,6483,125,EOI,Eledone cirrhosa,Pulpo blanco,Horned octopus,"spezies, mapdescar",2020-09-29,18,1448,1.448,138,1448,N10,-9.1271,42.0547,0101000020E6100000A9A44E40134122C0AC8BDB680007...
3,105,140600,6483,125,EOI,Eledone cirrhosa,Pulpo blanco,Horned octopus,"spezies, mapdescar",2020-09-29,10,475,0.475,104,475,N10,-8.9856,42.0859,0101000020E61000000DE02D90A0F821C0FB5C6DC5FE0A...
4,106,140600,6483,125,EOI,Eledone cirrhosa,Pulpo blanco,Horned octopus,"spezies, mapdescar",2020-09-29,7,1180,1.18,133,1180,N10,-9.0694,42.1569,0101000020E61000004FAF9465882322C0075F984C1514...

## Filtrando datos

Imos cargar o dataframe de `capturas` para filtrar os datos e quedarnos só cos datos de captura para o *Bacalao do Atlántico* (`cod_ieem 3582`).

In [6]:
bacalao = capturas.filter(col('spanish_fao_name') == 'Bacalao del Atlántico')

Consultamos cantas filas ten o conxunto xa filtrado.

In [7]:
bacalao.count()

1310

Observamos o filtrado realizado.

In [8]:
bacalao.limit(5).toPandas()

,id_observation,aphia_id_code,cod_ieem,id_spezie,x3a_code,scientific_name,spanish_fao_name,english_fao_name,project,obs_date,individuals,weight_gr,weight_kg,depth,weight_gr_dum,camp,long_4326,lat_4326,geom
0,136233,126436,3582,140,COD,Gadus morhua,Bacalao del Atlántico,Atlantic cod,spezies,NULL,0,0,0,114,NULL,N10,-9.0427,41.974,0101000020E610000012143FC6DC1522C0E9263108ACFC...
1,136234,126436,3582,140,COD,Gadus morhua,Bacalao del Atlántico,Atlantic cod,spezies,NULL,0,0,0,138,NULL,N10,-9.1271,42.0547,0101000020E6100000A9A44E40134122C0AC8BDB680007...
2,136235,126436,3582,140,COD,Gadus morhua,Bacalao del Atlántico,Atlantic cod,spezies,NULL,0,0,0,104,NULL,N10,-8.9856,42.0859,0101000020E61000000DE02D90A0F821C0FB5C6DC5FE0A...
3,136236,126436,3582,140,COD,Gadus morhua,Bacalao del Atlántico,Atlantic cod,spezies,NULL,0,0,0,133,NULL,N10,-9.0694,42.1569,0101000020E61000004FAF9465882322C0075F984C1514...
4,136237,126436,3582,140,COD,Gadus morhua,Bacalao del Atlántico,Atlantic cod,spezies,NULL,0,0,0,171,NULL,N10,-9.3073,41.9938,0101000020E6100000211FF46C569D22C0E561A1D634FF...